# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# C:\ci\containers\0000179qeev\tmp\build\80754af9\rsync-recipes\lzo-2.10-c_compilervs2015-on-winbuilder, last modified Tue Nov 21 11:55:21 2017
# ------------------------------------------------

package:
    name: lzo
    version: '2.10'
source:
    sha256: c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072
    url: http://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz
build:
    number: '2'
    run_exports:
        - lzo >=2.10,<3.0a0
    string: h6df0209_2
requirements:
    build:
        - cmake 3.9.4 h4b83b1b_0
        - vc 14 h2379b0c_2
        - vs2015_runtime 14.0.25123 hd4c4e62_2
        - vs2015_win-64 14.0.25123 hf5d5b87_2
    run:
        - vc 14.*
test:
    commands:
        - if not exist %PREFIX%\\Library\\include\\lzo\\lzoconf.h exit 1
        - if not exist %PREFIX%\\Library\\lib\\lzo2.lib exit 1
        - if not exist %PREFIX%\\Library\\lib\\lzo2_dllimport.lib exit 1
        - if not exist %PREFIX%\\Library\\bin\\lzo2.dll exit 1
about:
    description: 'LZO offers pretty fast compression and extremely fast decompression.

        MiniLZO is a very lightweight subset of the LZO library.

        '
    home: http://www.oberhumer.com/opensource/lzo/
    license: GPL v2+
    license_family: GPL2
    license_file: COPYING
    summary: LZO is a portable lossless data compression library written in ANSI C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - rmax
